USE haebeop;

CREATE DATABASE haebeop;

CREATE TABLE user (
id VARCHAR(200) PRIMARY KEY,
pw VARCHAR(300) NOT NULL,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
tel VARCHAR(100) NOT NULL,
addr1 VARCHAR(100) NOT NULL,
addr2 VARCHAR(100) NOT NULL,
postcode VARCHAR(100) NOT NULL,
regdate timestamp NOT NULL default CURRENT_TIMESTAMP,
birth VARCHAR(100) NOT NULL,
pt INT DEFAULT 0,
visited INT DEFAULT 0
);

INSERT INTO user VALUES('admin', '$2a$10$B1eSQwtXQMZIht3sHOWS7.a/wOmnXT9T3EqYwl7qBbOfAuj8YuKvW', '관리자', 'admin@haebeop.com','010-1234-1234', '서울', '구로동', '12345', DEFAULT, '1900-01-01', DEFAULT, DEFAULT );

DROP TABLE user;

select * FROM user;

CREATE table notice (
no INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200) NOT NULL,
content VARCHAR(3000) NOT NULL,
regdate DATE DEFAULT CURRENT_TIME,
visit INT(20) DEFAULT 0
);

DROP TABLE notice;

CREATE TABLE ARCHIVE (
ano INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200) NOT NULL,
content VARCHAR(3000) NOT NULL,
FILE1 VARCHAR(1000),
FILE2 VARCHAR(1000),
FILE3 VARCHAR(1000),
regdate DATE DEFAULT CURRENT_TIME,
author VARCHAR(200) NOT NULL,
visit INT(20)
);

CREATE TABLE subj (
scode INT AUTO_INCREMENT PRIMARY KEY,
stitle VARCHAR(200) NOT NULL,
sprice INT(20)
);

CREATE TABLE lecture (
lcode INT AUTO_INCREMENT PRIMARY KEY,
ltitle VARCHAR(200) NOT NULL,
lfile VARCHAR(1000),
scode INT,
bcode VARCHAR(100) NOT NULL,
tcode int NOT NULL,
totsdent INT(20)
);

DROP TABLE lecture;

CREATE TABLE slec (
slcode INT AUTO_INCREMENT PRIMARY KEY,
lcode INT,
stid VARCHAR(200),
totlect INT(20),
ltf BOOLEAN
);

CREATE TABLE teacher (
tcode INT AUTO_INCREMENT PRIMARY key,
tname VARCHAR(200) NOT NULL,
ttel VARCHAR(20) NOT NULL,
tmail VARCHAR(50) NOT null
);

DROP TABLE teacher;

CREATE TABLE txtbook (
txtcode INT AUTO_INCREMENT PRIMARY KEY,
txttitle VARCHAR(200) NOT NULL,
txtindx VARCHAR(3000),
txtpub VARCHAR(200),
pdate VARCHAR(20),
txtauthor VARCHAR(200),
price INT(20),
memo VARCHAR(500)
);