USE haebeop;

CREATE table notice (
no INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200) NOT NULL,
content VARCHAR(3000) NOT NULL,
regdate DATE DEFAULT CURRENT_TIME,
visit INT(20)
);

CREATE TABLE ARCHIVE (
ano INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200) NOT NULL,
content VARCHAR(3000) NOT NULL,
FILE1 VARCHAR(1000),
FILE2 VARCHAR(1000),
FILE3 VARCHAR(1000),
regdate DATE DEFAULT CURRENT_TIME,
author VARCHAR(200) NOT NULL,
visit INT(20)
);

CREATE TABLE subj (
scode INT AUTO_INCREMENT PRIMARY KEY,
stitle VARCHAR(200) NOT NULL,
sprice INT(20)
);

CREATE TABLE lecture (
lcode INT AUTO_INCREMENT PRIMARY KEY,
ltitle VARCHAR(200) NOT NULL,
lfile VARCHAR(1000),
scode INT,
bcode VARCHAR(100) NOT NULL,
tcode int NOT NULL,
totsdent INT(20)
);

DROP TABLE lecture;

CREATE TABLE slec (
slcode INT AUTO_INCREMENT PRIMARY KEY,
lcode INT,
stid VARCHAR(200),
totlect INT(20),
ltf BOOLEAN
);

CREATE TABLE teacher (
tcode INT AUTO_INCREMENT PRIMARY key,
tname VARCHAR(200) NOT NULL,
ttel VARCHAR(20) NOT NULL,
tmail VARCHAR(50) NOT null
);

DROP TABLE teacher;

CREATE TABLE txtbook (
txtcode INT AUTO_INCREMENT PRIMARY KEY,
txttitle VARCHAR(200) NOT NULL,
txtindx VARCHAR(3000),
txtpub VARCHAR(200),
pdate VARCHAR(20),
txtauthor VARCHAR(200),
price INT(20),
memo VARCHAR(500)
);